CREATE  TABLE  INGREDIENT_COST(
INGREDIENT_ID INT NOT NULL,
INGREDIENT_NAME  VARCHAR(50) NOT NULL,
UNIT_COST DOUBLE  NOT NULL
);

CREATE TABLE DRINK_ITEMS(
    DRINK_ID INT NOT NULL,
    DRINK_NAME VARCHAR(50) NOT NULL,
    DECAFE_COFEE INT NOT NULL,
    SUGAR INT NOT NULL,
    CREAM INT NOT NULL,
    STEAMED_MILK INT NOT NULL,
    FOAMED_MILK INT NOT NULL,
    ESPRESSO INT NOT NULL,
    COCOA INT NOT NULL,
    WHIPPED_CREAM INT NOT NULL
)